dist: precise
language: node_js
node_js:
  - "7"
services:
  - postgresql
before_script:
 - npm install -g gulp-cli
 - npm install -g sequelize-cli
 - npm install -g  istanbul@1.0.0-alpha.2
 - psql -c 'create database travis_ci_test;' -U postgres 
 - sequelize db:migrate
 - sequelize db:seed:all
script: gulp test
after_success:
  - npm install -g codeclimate-test-reporter
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - codeclimate-test-reporter < lcov.info
