dist: precise
language: node_js
node_js:
  - "7"
services:
  - postgresql
before_script:
 - npm install -g gulp-cli
 - npm install -g sequelize-cli
 - npm install -g  istanbul@1.0.0-alpha.2
 - npm install
script: gulp test
after_success:
  ./node_modules/.bin/coveralls --verbose < coverage/lcov.info
