development:
  adapter: postgresql
  database: <%= ENV['DATABASE_NAME_DEVELOPMENT'] %>
  encoding: utf8
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

test: &test
  adapter: postgresql
  database: <%= ENV['DATABASE_NAME_TEST'] %>
  encoding: utf8
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

api_test: &api_test
  adapter: postgresql
  database: api_<%= ENV['DATABASE_NAME_TEST'] %>
  encoding: utf8
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %