const ErrorConstants = {
  badJSONRequest: 'you are sending an invalid json object',
  invalidEndpointError: 'the endpoint you are trying to use is not available',
  genericErrorMessage: 'an error occured while trying to access this endpoint.',
  emptySearchString: 'please provide queryString \'q\'',
  userAuthErrors: {
    conflictingPasswordError: 'confirmation password and password should match',
    badEmailError: 'badly formatted email',
    incompleteCredentialsError: 'incomplete credential provided',
    duplicateEmailError: 'this email is already used',
    duplicateUsernameError: 'this username is already used',
    wrongEmailOrPassword: 'wrong email or password',
    wrongPasswordError: 'provide the right password to complete this action',
    userNotFound: 'sorry. user not found',
    unAuthorizedUserError: 'you are not authorized to complete this action',
  },
  endOfPageReached: 'you have reached end of the page',
  unmatchedUserSearch: 'your query does not match any email in our database',
  voidUserDeleteError: 'the user you tried to delete is not on docman',
  userDeleteUnauthorizedError: 'sorry! you can only delete your own account',
  genericUserUpdateError: 'unfortunately, an occured while updating user ',
  passwordUpdateError: 'confirmationPassword and newPassword does not match',
  fullNameLimitError: 'you have exceeded the character limit(25) for fullName',
  usernameLimitError: 'username should be 4 to 15 characters',
  bioLimitError: 'your bio should not have more than 240 characters.',
  userNotFound: 'there is no user with that Id in the database',
  paginationQueryError: 'sorry, limit and offset shoud be numbers',
  wrongIdTypeError: 'param \'id\' should be a number',
  duplicateDocTitleError: 'duplicate document title not allowed',
  invalidDocAccessLevelError: 'access can either be public, private or role',
  documentTitleLimitError: 'title should be between 1 to 30 characters',
  documentContentLimitError: 'content should be between 1 to 10000 characters',
  genericCreateDocumentError: 'document create failed due to server error',
  nullDocumentUpdateError: 'the document you tried to update does not exist',
  emptyDocumentUpdateError: 'you did not provide any field to update',
  unauthorizedDocumentUpdateError: 'sorry, you can only edit your own document',
  voidDocumentDeleteError: 'the document you tried to update was not found',
  documentDeleteUnauthorizedError: 'you can only delete your own document',
  fileQueryForbiddenError: 'sorry, you are not permitted to view this file',
  noDocumentFoundError: 'no document found',
  documentNotFound: 'no document found',
  badDocumentsQuery: 'query string q cannot be empty',
  badMethodError: 'this api only takes one POST, PUT, DELETE AND GET methods',
  errorCodes: {
    errNoDefaultForField: '1364',
    erDupEntry: '23505',
    notAnInt: '22P02',
    invalidEnumInput: '22P02'
  },
};
export default ErrorConstants;
